#ifndef MOBYUTIL_H
#define MOBYUTIL_H

#include "types.h"

// 16-byte vector. The original class stores a single 128-bit value (the
// Deadlocked symbols show one 128-bit member, hence the old s128 spelling),
// but this EGC has no 16-byte scalar type, so the components are spelled
// out. sizeof(vec4) == 16 is what the original layout requires: the
// 0x100-byte MobyInstance stride (addiu s0,s0,0x100 in CreateMoby) only
// closes with 16-byte vec4 members.
struct vec4 {
    f32 x;
    f32 y;
    f32 z;
    f32 w;
/*
    vec4& operator=();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4();
    vec4x VecX();
    vec4y VecY();
    vec4z VecZ();
    vec4w VecW();
    void SetFromVec();
    void SetX();
    void SetY();
    void SetZ();
    void SetW();
    void SetW();
    void SetXY();
    void SetXZ();
    void SetXW();
    void SetYZ();
    void SetYW();
    void SetZW();
    void SetXYZ();
    void SetXYW();
    void SetXZW();
    void SetYZW();
    void SetXYZW();
    void Set();
    void Set();
    void SetX();
    void SetY();
    void SetZ();
    void SetW();
    void SetXY();
    void SetXZ();
    void SetXW();
    void SetYZ();
    void SetYW();
    void SetZW();
    void SetXYZ();
    void SetXYW();
    void SetXZW();
    void SetYZW();
    void SetXYZW();
    void Set();
    f32 operator[]();
    vec4 operator-();
    vec4 operator+();
    vec4 operator-();
    vec4 operator*();
    vec4 operator/();
    vec4 operator+=();
    vec4 operator-=();
    vec4 operator*=();
    vec4 operator/=();
    vec4 operator+();
    vec4 operator-();
    vec4 operator*();
    vec4 operator+=();
    vec4 operator-=();
    vec4 operator*=();
    vec4 operator+();
    vec4 operator+();
    vec4 operator+();
    vec4 operator+();
    vec4 operator-();
    vec4 operator-();
    vec4 operator-();
    vec4 operator-();
    vec4 operator*();
    vec4 operator*();
    vec4 operator*();
    vec4 operator*();
    vec4 operator/();
    vec4 operator/();
    vec4 operator/();
    vec4 operator/();
    vec4 operator+=();
    vec4 operator+=();
    vec4 operator+=();
    vec4 operator+=();
    vec4 operator-=();
    vec4 operator-=();
    vec4 operator-=();
    vec4 operator-=();
    vec4 operator*=();
    vec4 operator*=();
    vec4 operator*=();
    vec4 operator*=();
    vec4 operator/=();
    vec4 operator/=();
    vec4 operator/=();
    vec4 operator/=();
    vec4 operator*=();
    vec4 operator*=();
    void AddX();
    void AddY();
    void AddZ();
    void AddW();
    void SubX();
    void SubY();
    void SubZ();
    void SubW();
    void MulX();
    void MulY();
    void MulZ();
    void MulW();
    void NegX();
    void NegY();
    void NegZ();
    void NegW();
    void MinX();
    void MinY();
    void MinZ();
    void MinW();
    void MaxX();
    void MaxY();
    void MaxZ();
    void MaxW();
    void ClampX();
    void ClampY();
    void ClampZ();
    void ClampW();
    void LimitX();
    void LimitY();
    void LimitZ();
    void LimitW();
    vec4x Sum2();
    vec4x Len2();
    vec4x InvLen2();
    vec4x LenSquared2();
    vec4 Normalized2();
    void Normalize2();
    vec4x Sum3();
    vec4x Len3();
    vec4x InvLen3();
    vec4x LenSquared3();
    vec4 Normalized3();
    void Normalize3();
    vec4x Sum4();
    vec4x Len4();
    vec4x InvLen4();
    vec4x LenSquared4();
    vec4 Normalized4();
    void Normalize4();*/
};

#endif
