name: Ratchet & Clank (USA)
sha1: 72fd1de379dafd8f243dceeb3be50980f3fd3cd5 

options:
  basename: SCUS_971.99
  target_path: assets/boot_elf.elf
  elf_path: SCUS_971.99
  base_path: ../
  platform: ps2
  compiler: EEGCC

  asm_path: code/_generated
  src_path: code/
  data_path: build/data
  build_path: build
  o_as_suffix: True  # otherwise splat will try to link with e.g. .cpp.o

  find_file_boundaries: False
  disasm_unknown: False
  named_regs_for_c_funcs: False

  pair_rodata_to_text: False  # Not having this crashes splat
  rodata_string_guesser_level: 0

  # We probably need this at some point:
  # https://github.com/ethteck/splat/wiki/Configuration#gp_value

  # Might want this later
  generate_asm_macros_files: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: build/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: build/undefined_syms_auto.txt
  symbol_addrs_path: config/symbols.txt

  ld_legacy_generation: True


  check_consecutive_segment_types: False

  # Not handling overlays here at all yet. 

  # Sly1 and KH1 decomps use this, I'm assuming we want to too.
  subalign: 8

segments:
  - [0, databin, elf_header]

  - { start: 0x1000, type: data, name: vutext, linker_section: .vutext, vram: 0x100080 }

  - name: core.text
    type: code
    start: 0x13300
    vram: 0x112380
    subsegments:
    - [0x13300, asm, core_text1]  # core.text
    - [0x16448, c, stubs]
    - [0x16450, asm, core_text4]
    - [0x2e6a8, asm, sce/crt0] 
    - [0x2e868, asm, core_text2]

  - name: core.data
    type: data
    start: 0x30400
    vram: 0x0012f480

  - name: core.rdata
    type: rdata
    start: 0x53180
    vram: 0x00152200

  - name: core.bss
    type: data
    bss_size: 0xab20
    pair_segment: core.text
    start: 0x55080
    vram: 0x00154100

  - name: core.lit
    type: lit4
    start: 0x5fc00
    vram: 0x0015ec80

  - name: lit
    type: lit4
    start: 0x5fe80
    vram: 0x0015ef00

  - name: bss
    type: data
    pair_segment: text
    start: 0x62200
    vram: 0x00161280

  - name: data
    type: data
    start: 0x66400
    vram: 0x00165480

  - name: lvl.vtbl
    type: rodata
    start: 0xe9b00
    vram: 0x1e8b80

  - name: lvl.camvtbl
    type: rodata
    start: 0xe9b80
    vram: 0x1e8c00

  - name: lvl.sndvtbl
    type: rodata
    start: 0xe9c00
    vram: 0x1e8c80

  - name: text
    type: code
    start: 0xe9c80
    vram: 0x1e8d00
    # bss_size: 0x41b0

    subsegments:
    # .text
    - [0xe9c80, asm, game/text1]

    - [0xea5d8, cpp, game/boot]

    - [0xeaa38, asm, game/text2]

  - [0x13e2e0, databin, overlays]
  - [0x1510EA, databin, section_headers]  # section headers
  - [0x151a74]
