name: Ratchet & Clank (USA)
sha1: 72fd1de379dafd8f243dceeb3be50980f3fd3cd5 

options:
  basename: SCUS_971.99
  target_path: assets/boot_elf.elf
  elf_path: SCUS_971.99
  base_path: ../
  platform: ps2
  compiler: EEGCC

  asm_path: code/_generated
  src_path: code/
  data_path: build/data
  build_path: build
  o_as_suffix: True  # otherwise splat will try to link with e.g. .cpp.o

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False

  pair_rodata_to_text: False  # Not having this crashes splat
  rodata_string_guesser_level: 0

  # We probably need this at some point:
  # https://github.com/ethteck/splat/wiki/Configuration#gp_value

  # Might want this later
  generate_asm_macros_files: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: build/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: build/undefined_syms_auto.txt
  symbol_addrs_path: config/symbols.txt

  ld_legacy_generation: True


  check_consecutive_segment_types: False

  # Not handling overlays here at all yet. 

  # Sly1 and KH1 decomps use this, I'm assuming we want to too.
  subalign: 8

segments:
  - [0, databin, elf_header]

  - { start: 0x1000, type: data, name: vutext, linker_section: .vutext, vram: 0x100080 }

  - name: core.text
    type: code
    start: 0x13300
    vram: 0x112380
    subsegments:
    - [0x13300, asm, glibc]
    - [0x196d0, asm, sce/lib]
    - [0x2e6a8, asm, sce/crt0]
    - [0x2e878, cpp, game/boot]
    - [0x2e9a8, c, 989snd/ee/989snd]
    - [0x30148, cpp, game/permcb]
    - [0x30188, cpp, game/wad]

  - name: core.data
    type: data
    start: 0x30400
    vram: 0x0012f480

  - name: core.rdata
    type: rdata
    start: 0x53180
    vram: 0x00152200

  - name: core.bss
    type: data
    bss_size: 0xab20
    pair_segment: core.text
    start: 0x55080
    vram: 0x00154100

  - name: core.lit
    type: lit4
    start: 0x5fc00
    vram: 0x0015ec80

  - name: lit
    type: lit4
    start: 0x5fe80
    vram: 0x0015ef00

  - name: bss
    type: data
    pair_segment: text
    start: 0x62200
    vram: 0x00161280

  - name: data
    type: data
    start: 0x66400
    vram: 0x00165480

  - name: lvl.vtbl
    type: rodata
    start: 0xe9b00
    vram: 0x1e8b80

  - name: lvl.camvtbl
    type: rodata
    start: 0xe9b80
    vram: 0x1e8c00

  - name: lvl.sndvtbl
    type: rodata
    start: 0xe9c00
    vram: 0x1e8c80

  - name: text
    type: code
    start: 0xe9c80
    vram: 0x1e8d00
    # bss_size: 0x41b0

    subsegments:
    # .text
    - [0xe9c80, cpp, game/actuator]
    - [0xea0e8, cpp, game/bloaders]
    - [0xea330, asm, game/stub]
    - [0xea408, cpp, game/bmain]
    - [0xeaa38, cpp, game/transition]
    - [0xecc10, cpp, game/camera]
    - [0xeebd0, cpp, game/effects] # Probably the wrong name for this, but it's neither camera or cmecpu 
    - [0xef5d0, asm, game/cmecpu]
    - [0xf0948, asm, game/collproc]
    - [0xf1b08, cpp, game/draw]
    - [0xf8a18, asm, game/drawquad]
    - [0xfa5c8, asm, game/fastfunc]
    - [0xfb7e0, cpp, game/framebuf]
    - [0xfca38, cpp, game/freeze]
    - [0xfe660, cpp, game/help]
    - [0xffdb8, cpp, game/hud]
    - [0x1024a0, cpp, game/init]
    - [0x102558, cpp, game/initonce]
    - [0x1029a8, cpp, game/lights]
    - [0x1031f0, cpp, game/loaders]
    - [0x105c70, cpp, game/map]     # Lots of things that are referenced in draw_map_screen which is part of pause.cpp
    - [0x1078f8, cpp, game/menu]    # Just a guess, could be slightly later
    - [0x109798, cpp, game/menu_callbacks]
    - [0x109850, cpp, game/menu_post]
    - [0x109fb0, cpp, game/memcard]
    - [0x10c340, asm, game/miscproc]
    - [0x10c8d0, asm, game/missionfunc] # Referenced in some map func stuff
    - [0x10d478, cpp, game/mobyfunc]
    - [0x10e7e8, asm, game/mobyproc]  # Insomniac handwrote this
    - [0x113ba8, cpp, game/mobyutil]  # Not sure about this split, could be something towards the end of this file that isnt related to mobyutil
    - [0x116310, cpp, game/music]
    - [0x117668, cpp, game/stream]
    - [0x118048, cpp, game/pad]
    - [0x1189b0, asm, game/partproc]  # Insomniac handwrote this
    - [0x119808, cpp, game/partupd]
    - [0x119c90, cpp, game/pause] 
    - [0x1286c0, asm, game/shadowproc]
    - [0x129870, cpp, game/shrubfunc]
    - [0x129b68, asm, game/shrubproc]
    - [0x12bbb0, cpp, game/skyfunc]
    - [0x12cb20, asm, game/skyproc]
    - [0x12d528, cpp, game/sound]
    - [0x12ed90, cpp, game/space]
    - [0x133c60, cpp, game/stash]
    - [0x133fe8, cpp, game/tfragfunc]
    - [0x134458, cpp, game/vuchain]
    - [0x134f30, asm, game/tfragproc] # Insomniac handwrote this
    - [0x1365c0, cpp, game/tiefunc]
    - [0x136b68, asm, game/tieproc]
    - [0x1389f0, cpp, game/update]   # 00237a70
    - [0x139290, cpp, game/vendor]
    - [0x13b338, cpp, game/movie/movie]
    - [0x13bb50, cpp, game/movie/audiodec]
    - [0x13c190, cpp, game/movie/disp]
    - [0x13c570, cpp, game/movie/read]
    - [0x13c8c0, cpp, game/movie/readbuf]
    - [0x13c9c8, cpp, game/movie/strfile]
    - [0x13ca78, cpp, game/movie/vibuf]
    - [0x13da48, cpp, game/movie/videodec]
    - [0x13e110, cpp, game/movie/vobuf]

  - [0x13e2e0, databin, overlays]
  - [0x1510EA, databin, section_headers]  # section headers
  - [0x151a74]
